slave:
  slave_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - base_arm1_Joint
      - arm1_arm2_Joint
      - arm2_arm3_Joint
      - arm3_arm4_Joint
      - arm4_arm5_Joint
      - arm5_arm6_Joint

    gains:
      base_arm1_Joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm1_arm2_Joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm2_arm3_Joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm3_arm4_Joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm4_arm5_Joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm5_arm6_Joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

#gripper_controller:  
#type: "position_controllers/JointTrajectoryController"  
#joints:  
#          - finger_joint1  
#          - finger_joint2  
#gains:  
#finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}  
#finger_joint2:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}  
